### ISSUE TITLE
Highlighting issues on VS2017 and dark theme

### ISSUE THREAD

**Issue by jpozo20** [Ant-f/WorkingFilesList#10]
It seems like there is a problem withe the highlight on VS2017 with the Dark theme, the names are not correctly highlighted and they are highlighted even is the option is disabled.

Image:
<img width="261" alt="screen shot 2017-05-15 at 11 00 09 pm" src="https://cloud.githubusercontent.com/assets/9166182/26088084/f88d3870-39c2-11e7-88e4-d3bb0d2b0efc.png">

**Comment by Ant-f** [comment]
Could you elaborate on what you mean when you say that the names are not highlighting correctly? Do you mean that toggling the option checkbox on and off does not do anything? This is a bug; the workaround for now would be to change the _File Name Segments_ (between the sorting options drop-downs and the _Options_ button) to refresh each list entry. The value can be set back to the original value afterwards.

**Comment by jpozo20** [comment]
> Do you mean that toggling the option checkbox on and off does not do anything? 

Yes, the highlighting stays even if you disable it.

> Could you elaborate on what you mean when you say that the names are not highlighting correctly? 

I think the highlighting should either cover the whole line, or just the file name. But as you see on the picture, some files have the whole line highlighted; others the whole name of the file, and others just part of the name.

**Comment by Ant-f** [comment]
Ah... I think I understand.

When highlighting is on, the file name text is highlighted; the text for the file extension and any directory names are lowlighted. I've modified the highlight/lowlight ratio in an upcoming build to increase the highlighting effect.

The length coloured bars behind the text are related to the _Show most recently used order_ option; the more recently a file has been selected (in relation to the others), the longer the bar is. To have the bar fill the entire width of the window, disable _Show most recently used order_.

**Comment by Ant-f** [comment]
Addressed in v1.2:
* Filename highlighting preference is applied immediately after selection
* Filename-to-path/extension highlight/lowlight ratio adjusted
