### ISSUE TITLE
 sometimes the file name still exists in the working file list window

### ISSUE THREAD

**Issue by sxf359** [Ant-f/WorkingFilesList#15]
The file is closed, but sometimes the file name still exists in the working file list window. Click delete, but it will not be deleted. It will also exist.
visual studio 2015 Enterprise Edition

**Comment by Ant-f** [comment]
Would you be able to provide more information about this? e.g.

* Does this happen frequently, or is it quite rare?
* Does it happen with a particular project, or maybe a particular project type (e.g. C# library)?
* Does the file that is closed (but remains visible in Working Files List) disappear after closing another file? [closing a file should trigger a resync of the list]

If there are any steps that can reliably recreate this issue, it would contribute greatly towards being able to fix it.

**Comment by sxf359** [comment]
Thank you for your attention.
This problem occurs when I double-click a file in window of the Working File List， It will be top, It will also appear in the project area, when I clicked the file's Close button, the project area has not shown the file, but the top area will still be displayed. I would like to click the file's Close button，The workspace does not display this file

**Comment by Ant-f** [comment]
A single left click will select/activate files within Working Files List, similar to how a single click will activate files on Visual Studio's file tabs. A double-click will pin files, moving them up to the top of the Working Files List window. Pinned files also remain when the file-editor window has been closed; to remove the entry, unpin the file by moving the mouse over it and clicking on the pin button. This behaviour was introduced in version 1.2, after being raised as a [feature request](https://github.com/Ant-f/WorkingFilesList/issues/9).

**Comment by sxf359** [comment]
sorry, I don't know how to do it.As you say, it's really feasible, thank you.
