### ISSUE TITLE
Extension not loading :( Throws exception

### ISSUE THREAD

**Issue by sibkot** [Ant-f/WorkingFilesList#21]
ActivityLog.xml 
  <entry>
    <record>1854</record>
    <time>2019/05/15 10:55:46.974</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WorkingFilesWindowPackage]Source: &apos;WorkingFilesList.ToolWindow&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at WorkingFilesList.ToolWindow.ViewModel.DocumentMetadataManager.Synchronize(Documents documents, Boolean setUsageOrder)&#x000D;&#x000A;   at WorkingFilesList.WorkingFilesWindowPackage.InitializeServices(IKernel kernel, IOptionsPageService optionsPageService) in E:\Git\WorkingFilesList\Solution\WorkingFilesList\WorkingFilesWindowPackage.cs:line 142&#x000D;&#x000A;   at WorkingFilesList.WorkingFilesWindowPackage.&lt;InitializeAsync&gt;d__3.MoveNext() in E:\Git\WorkingFilesList\Solution\WorkingFilesList\WorkingFilesWindowPackage.cs:line 111&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.ThreadingTools.&lt;WithCancellationSlow&gt;d__12.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask`1.Join(CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.&lt;&gt;c__DisplayClass24_1`1.&lt;AsVsTask&gt;b__2()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{26BF5782-13D2-4168-B979-BFCDE9BD63DD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by Ant-f** [comment]
Hi

This seems similar to #12. The stack trace looks a little different because the initialization has since been converted to be async. Is this the first time that you've tried running the plugin, or was it running ok previously?

If the latter, is it possible that a recent update of Visual Studio/another plugin modified something: maybe you could try uninstalling Working Files List and re-installing it?

If this is the first time that you've tried to use Working Files List, which version of Visual Studio are you running, and is it the latest Update version? I've recently seen it run successfully on 15.9.11, 15.9.12, 16.0.3, and 16.0.4.

**Comment by Ant-f** [comment]
Closing issue after 13 days of inactivity; will reopen if necessary.
