### ISSUE TITLE
Package failed to load: FileNotFoundException

### ISSUE THREAD

**Issue by oleneveu** [Ant-f/WorkingFilesList#22]
Hi,

The WorkingFileList package failed to load when opening a solution, where a source file in one of the projects had been removed recently.
I've attached the activity log from VS.

I suspect that the extension is trying to load the 'ValuesController.cs' file while it is not available anymore in the solution.

Edit: I've managed to reproduce the issue:
- Create a new console project in VS, the add a 'class1.cs' file to that project.
- Close VS, and from the Windows file explorer delete the 'class1.cs' file.
- Reopen VS and the solution, the issue will occur. You will need to close VS to have the extension working again.

Regards,

[ActivityLog.zip](https://github.com/Ant-f/WorkingFilesList/files/3397175/ActivityLog.zip)

**Comment by Ant-f** [comment]
Issue should be fixed in [v1.8.0](https://github.com/Ant-f/WorkingFilesList/releases/tag/v1.8.0)
