### ISSUE TITLE
suggestion: hide the bars

### ISSUE THREAD

**Issue by muellerto** [Ant-f/WorkingFilesList#30]
Would it be possible to have an option that **hides the button and search bars** at the top of the window? The window itself is good and useful but I don't need the bars.

The button bar has some functionality of the options page. But I did set the options weeks ago and it runs since then exactly like that. I never use these buttons in daily work, not one of them. The same with the search bar. I can remember what I have open, I must never search one of my seven or ten open files. (I know, other people have 50 or more files open, but this is not me.)

The options are always available in the Tools|Options menu, so the user can always switch the bars on  again when this should be needed.

Note: These two bars consume a constant hight of about 15mm which I call wasted. This comes on top of the Solution Explorer which also wastes 15mm. I would like to use this vertical space for something more useful.

**Comment by Ant-f** [comment]
Please upgrade to version 1.6.0 for this feature

**Comment by muellerto** [comment]
Great! Thanks a lot for that.
