### ISSUE TITLE
File Icons, pls

### ISSUE THREAD

**Issue by NikolaMancic** [Ant-f/WorkingFilesList#4]
As a user of this plugin
I want to see file type icons in the _Working File List_
So that I can _easily distinguish_ files with the same name, but different extensions (fs, cs, vb. etc)
And it makes the whole user experience more **visually appealing**

**Comment by Ant-f** [comment]
Adding icons for the following file types:

.config/.cpp/.cs/.fs/.js/.txt/.ts/.vb/.xaml
