### ISSUE TITLE
Abilitity to Pin Files

### ISSUE THREAD

**Issue by jnkb** [Ant-f/WorkingFilesList#9]
It would be very useful if we could pin files to the top with changeable order.
Maybe in a separate "pined files" group before the first project?
The pinned files should stay there, even if they are closed.

**Comment by Ant-f** [comment]
By changeable order do you mean for example, the main list is sorted by most recent usage, and the pinned items are sorted A-Z?

**Comment by jnkb** [comment]
No, I meant, that the pinned items can be sorted via drag drop - no automatically sorting. 


![working_file_list_pinned_files](https://cloud.githubusercontent.com/assets/26929742/25372377/6c35794c-2995-11e7-979d-4fbfee30890c.png)
(screen is only photoshop)

**Comment by Ant-f** [comment]
Added in v1.2

**Comment by jnkb** [comment]
thanks! works great :)

it is possible to save the pinned status of the files between a restart of visual studio?

**Comment by Ant-f** [comment]
Saved pinned status should be available in version 1.4
